PPW_Story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects, name='projects'),
    path('story5/', views.story5, name='story5')
]

homepage/models.py
from django.db import models

# Create your models here.

class Year(models.Model):
    year = models.CharField(max_length=4, unique=True, primary_key=True)

    def __str__(self):
        return self.year

    class Meta:
        ordering = ['year']

class Friend(models.Model):
    full_name = models.CharField(max_length=100)
    student_id = models.CharField(max_length= 10, primary_key=True, unique=True)
    hobby = models.CharField(max_length=255)
    favorite_food = models.CharField(max_length=255)
    year = models.ForeignKey('Year', on_delete=models.CASCADE)

homepage/forms.py
from django import forms
from .models import Year

class Friend_Form(forms.Form):
    nameInput = {'id': 'forms', 'name' : 'fullname'}
    npmInput = {'id' : 'forms', 'name' : 'npm'}
    yearInput = {'id' : 'forms', 'name' : 'year'}
    year_choices = [('2016', '2016'), ('2017', '2017')]
    hobbyInput = {'id' : 'forms', 'name' : 'Hobby' }
    favInput = {'id' : 'forms', 'name' : 'Favorites'}

    name = forms.CharField(label='Name', required=True, max_length=100, widget=forms.TextInput(nameInput))

    npm = forms.CharField(label='NPM', required=True, max_length=10, widget=forms.TextInput(npmInput))

    hobby = forms.CharField(label='Hobby', required=True, max_length=255, widget=forms.TextInput(hobbyInput))

    favorite = forms.CharField(label='Favorites', required=True, max_length=255, widget=forms.TextInput(favInput))

    year = forms.ModelChoiceField(queryset = Year.objects.all() ,label='Year', required=True, widget=forms.Select(yearInput))

homepage/views.py
from django.shortcuts import render
from .models import Friend, Year
from .forms import Friend_Form

# Create your views here.

def index(request):
    return render(request, 'index.html')

def projects(request):

    return render(request, 'projects.html')

def story5(request):
    friend_list = Friend.objects.all()
    if request.method == 'POST':
        form = Friend_Form(request.POST)
        if form.is_valid():
            print(form.data)
            year = Year(form.data['year'])
            friend = Friend(full_name= form.data['name'], student_id = form.data['npm'], hobby = form.data['hobby'], favorite_food = form.data['favorite'], year = year)
            friend.save()
            blank = Friend_Form()
            form = {'form' : blank, 'friend_list' : friend_list}
            return render(request, 'story5.html', form)
    else:
        form = Friend_Form()  
        response = {'form' : form, 'friend_list' : friend_list}
        return render(request, 'story5.html', response)

homepage/templates/index.html
<!DOCTYPE html>
{%load static%}
<head>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}"/>

</head>
<body>
    <ul class="profile_navbar">
        <li>
            <a href="{% url 'homepage:index' %}" target="_self">HOME</a>
        </li>
        <li>
            <a href="{% url 'homepage:projects' %}" target="_self">PROJECTS</a>
        </li>
        <li>
            <a href="{% url 'homepage:index' %}#contacts" onclick="scrollTo('contacts')">CONTACTS</a>
        </li>
    </ul>
    <div class="main">
        <div class="profile_container">
            <div class="profile_container_sect" style="flex-basis: 100%;">
                <h1 id="title_text">
                    Faza Aulia Aryoga
                </h1>
                <h2 id="title_text">
                    Student at University of Indonesia
                </h2>
                <img src="{% static 'Faza Aulia Aryoga.jpg' %}" alt="profile pic" style="height: 500px; width: 500px; border-radius: 50%; border: 3px solid black; margin: auto; padding: 3px;">
                <h3 id="title_text">
                    A 19 year old Computer Science student with a dream to be a game developer in the future. I learn about game development in my free time and i like playing games and archery
                </h3>
            </div>
        </div>
        <div class="profile_container">
            <h1 id="title_text" style="padding-top: 25px; padding-bottom: 25px;">
                SKILLS
            </h1>
            <img src="{% static 'Unity.png' %}" alt="UnityEngine" title="Unity Engine" id="skills_icon">
            <img src="{% static 'Unreal engine.png' %}" alt="Unreal Engine" title="Unreal Engine 4" id="skills_icon">
            <img src="{% static 'Java.png' %}" alt="Java" title="Java" id="skills_icon">
            <img src="{% static 'Python.png' %}" alt="Python" title="Python" id="skills_icon">
            <img src="{% static 'C sharp.png' %}" alt="C sharp" title="C#" id="skills_icon">

            <h1 id="title_text" style="padding-top: 25px; padding-bottom: 25px;">
                EDUCATION & WORK EXPERIENCE
            </h1>
            <ul>
                <li>
                    SMA Negeri 1 Depok 2015 - 2018
                </li>
                <li>
                    University of Indonesia 2018 - Present
                </li>
                <li>
                    placeholder
                </li>
                <li>
                    placeholder
                </li>
                <li>
                    placeholder
                </li>
            </ul>
        </div>
        <div class="profile_container">
            <h2 id="title_text" id="contacts">
                CONTACT ME
            </h2>
            <div id="contact_container">
                <img src="{% static 'Line.png' %}" alt="Line" id="skills_icon" onclick="on()">
                <a href="https://www.linkedin.com/in/faza-aryoga-77a2a61a1/" target="_blank">
                    <img src="{% static 'linkedin-logo-png-1825.png' %}" alt="linkedin" id="skills_icon">
                </a>
                <a href="https://steamcommunity.com/profiles/76561198127667028/" target="_blank">
                    <img src="{% static 'steam-icon-14883.png' %}" alt="steam" id="skills_icon">
                </a>
                <a href="https://www.instagram.com/faza_aryoga/" target="_blank">
                    <img src="{% static 'instagram-logo-png-2428.png' %}" alt="instagram" id="skills_icon">
                </a>
            </div>
        </div>

        <div id="line_overlay" onclick="off()">
            <div id="line_overlay_bg">
                <h4 id="title_text" style="color: black;">Use the QR Code scanner on your line</h4>
                    <img src="{% static 'my_qrcode_1580575791331.jpg' %}" alt="qr_code">
                <p id="title_text" style="color: black;">
                    LINE -> Friends -> Add Friends -> QR Code Scanner
                </p>
            </div>
        </div>
    </div>


    <script>
        // When the user scrolls down 20px from the top of the document, slide down the navbar
        var prevScrollpos = window.pageYOffset;
        window.onscroll = function() {
            var currentScrollPos = window.pageYOffset;
            if (prevScrollpos > currentScrollPos) {
                document.getElementsByClassName("profile_navbar")[0].style.top = "0";
            } else {
                document.getElementsByClassName("profile_navbar")[0].style.top = "-100px";
            }
            prevScrollpos = currentScrollPos;
        }

        function scrollTo(hash){
            location.hash = "#" + hash;
            console.log("Called")
        }

        function on() {
            document.getElementById("line_overlay").style.display = "block";
        }

        function off() {
            document.getElementById("line_overlay").style.display = "none";
        }
    </script>
</body>

homepage/templates/nav_copyright.html
<!DOCTYPE html>
<head>
</head>
<body>
    <div>
        Copyright &copy; 2020 Faza Aulia Aryoga. All rights reserved
    </div>
</body>

homepage/templates/projects.html
<!DOCTYPE html>
{%load static%}
<head>
    <title>Projects</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-body">
              THIS IS A MODAL
            </div>
          </div>
        </div>
      </div>
    <ul class="profile_navbar">
        <li>
            <a href="{% url 'homepage:index' %}">
                HOME
            </a>
        </li>
        <li>
            Project 1
        </li>
        <li>
            <a href="{% url 'homepage:story5' %}">
                Story 5
            </a>   
        </li>
        <li>
            <a data-toggle="modal" data-target="#exampleModalCenter">
                Launch demo modal
            </a>
        </li>
    </ul>
    <div class="main" style="width: 100%; height: 100%;">
        <div class="profile_container">
            This is a placeholder with more content to be added in the future
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

homepage/templates/story5.html
<!DOCTYPE html>
{%load static%}
<head>
    <title>
        Friend List
    </title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <ul class="profile_navbar">
        <li>
            <a href="{% url 'homepage:index' %}">
                HOME
            </a>
        </li>
        <li>
            Project 1
        </li>
        <li>
            Story 5
        </li>
        <li>
            <a data-toggle="modal" data-target="#exampleModalCenter">
                Launch demo modal
            </a>
        </li>
    </ul>
    <div class="main">
        <div class="profile_container">
            <form action="{% url 'homepage:story5' %}" method="POST">
                {% csrf_token %}
                <p>NAME:</p>
                {{ form.name }}
                <p>NPM:</p>
                {{ form.npm}}
                <p>Hobbies:</p>
                {{ form.hobby }}
                <p>Favorite food/drinks:</p>
                {{ form.favorite}}
                <p>YEAR:</p>
                {{ form.year }}
                <input type="submit" value="Submit">
            </form>
        </div>
        <div class="profile_container">
            <ul>
                {% for friends in friend_list %}
                <li>
                <h3>
                   {{ friends.full_name}}
                </h3>
                <p>
                   NPM: {{ friends.student_id }}
                </p>
                <p>
                    Hobbies: {{ friends.hobby }}
                </p>
                <p>
                    Favorite Food/Drinks: {{friends.favorite_food}}
                </p>
                <p>
                    Year: {{ friends.year.year }}
                </p>
                {% endfor %}
                </li> 
            </ul>
        </div>
    </div>
</body>